name: Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Log in to Google Container Registry
      # run: echo -n "${{ secrets.GCR_JSON_KEY }}" | base64
      run: echo "${{ secrets.GCR_JSON_KEY }}" | docker login -u _json_key --password-stdin https://gcr.io

    - name: Build and push backend Docker image
      run: |
        docker build -t gcr.io/final-project-434/backend:v1 .
        docker push gcr.io/final-project-434/backend:v1

    - name: Build and push frontend Docker image
      run: |
        cd frontend
        docker build -t gcr.io/final-project-434/frontend:v1 .
        docker push gcr.io/final-project-434/frontend:v1

    - name: Deploy to GKE
      uses: google-github-actions/deploy-gke@v0.0.1
      with:
        cluster_name: final434-cluster-1
        location: us-central1-a
        manifests: |
          backend-deployment.yaml
          frontend-deployment.yaml
        project_id: final-project-434
        credentials: ${{ secrets.GCP_SA_KEY }}
