name: Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Authenticate to Google
      uses: google-github-actions/auth@v2
      with:
        credentials_json: "${{ secrets.GCR_JSON_KEY }}"

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        install_components: "gke-gcloud-auth-plugin"

    - name: Authenticate to GKE cluster
      uses: google-github-actions/get-gke-credentials@v2
      with:
        cluster_name: final434-cluster-1
        location: us-central1-a

    - name: Log in to Google Container Registry
      run: echo ${{ secrets.GCR_JSON_KEY_BASE64 }} | base64 --decode | docker login -u _json_key --password-stdin https://gcr.io

    - name: Build and push backend Docker image
      run: |
        cd backend
        docker build -t gcr.io/final-project-434/backend:${{ github.sha }} .
        docker push gcr.io/final-project-434/backend:${{ github.sha }}

    - name: Build and push frontend Docker image
      run: |
        cd frontend
        docker build -t gcr.io/final-project-434/frontend:${{ github.sha }} .
        docker push gcr.io/final-project-434/frontend:${{ github.sha }}

    - name: Update Kubernetes deployment
      run: |
        kubectl set image deployment/backend-deployment backend=gcr.io/final-project-434/backend:${{ github.sha }}
        kubectl set image deployment/frontend-deployment frontend=gcr.io/final-project-434/frontend:${{ github.sha }}
